# Generated by Django 3.2.3 on 2021-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=15, null=True)),
                ('Month', models.CharField(max_length=15, null=True)),
                ('Date', models.CharField(max_length=15, null=True)),
                ('Day', models.CharField(max_length=15, null=True)),
                ('Post', models.TextField(max_length=1000, null=True)),
                ('Format', models.CharField(max_length=50, null=True)),
                ('Impressions', models.IntegerField(null=True)),
                ('ClickThroughrate', models.DecimalField(decimal_places=20, max_digits=50, null=True)),
                ('Retweets_Shares', models.IntegerField(null=True)),
                ('Likes', models.IntegerField(null=True)),
                ('Mediaviews', models.IntegerField(null=True)),
                ('Linkclicks', models.IntegerField(null=True)),
                ('Detailexpands', models.IntegerField(null=True)),
                ('Hashtagclicks', models.IntegerField(null=True)),
                ('Userprofileclicks', models.IntegerField(null=True)),
                ('Mediaengagements', models.IntegerField(null=True)),
                ('Totalengagement', models.IntegerField(null=True)),
                ('Engagements', models.IntegerField(null=True)),
                ('Follows', models.IntegerField(null=True)),
                ('Replies', models.IntegerField(null=True)),
                ('Fballclicks', models.IntegerField(null=True)),
                ('Time', models.IntegerField(null=True)),
                ('Totalengagement2', models.IntegerField(null=True)),
                ('PostLength', models.IntegerField(null=True)),
                ('Hashtags', models.IntegerField(null=True)),
                ('With_hash', models.IntegerField(null=True)),
                ('Mentions', models.IntegerField(null=True)),
                ('With_mentions', models.IntegerField(null=True)),
                ('Quater', models.CharField(max_length=2, null=True)),
                ('Word_count', models.IntegerField(null=True)),
            ],
        ),
    ]
